# Generated by Django 4.2.1 on 2023-05-29 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('futbol', '0002_jugador_index_page_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='partido',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('fecha', models.DateField()),
                ('goles_local', models.IntegerField()),
                ('goles_visitante', models.IntegerField()),
                ('equipo_local', models.ForeignKey(choices=[], on_delete=django.db.models.deletion.CASCADE, related_name='equipo_local_partido', to='futbol.equipo')),
                ('equipo_visitante', models.ForeignKey(choices=[], on_delete=django.db.models.deletion.CASCADE, related_name='equipo_visitante_partido', to='futbol.equipo')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
