# Generated by Django 4.2.1 on 2023-05-29 14:01

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('futbol', '0002_entrenador_index_page_equipo_index_delete_liga'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liga_Clasificacion_Page',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('nombre', models.CharField(max_length=250)),
                ('imagen', models.ImageField(upload_to='images/')),
                ('contenido', wagtail.fields.RichTextField(blank=True)),
                ('puntos', models.IntegerField()),
                ('partidos_jugados', models.IntegerField()),
                ('partidos_ganados', models.IntegerField()),
                ('partidos_empatados', models.IntegerField()),
                ('partidos_perdidos', models.IntegerField()),
                ('goles_favor', models.IntegerField()),
                ('goles_contra', models.IntegerField()),
                ('equipos', models.ManyToManyField(to='futbol.equipo')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
