# Generated by Django 4.2.1 on 2023-06-12 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futbol', '0003_entrenador_tags_entrenador_index_page_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='tags',
        ),
    ]
