# Generated by Django 4.2.1 on 2023-06-12 06:50

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eleccion',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('descripcion', wagtail.fields.RichTextField()),
                ('numero_votos', models.IntegerField(default=0)),
                ('region_pueblo_comunidad', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('nombre', models.CharField(max_length=100)),
                ('fundacion', models.DateField()),
                ('lider', models.CharField(max_length=100)),
                ('descripcion', wagtail.fields.RichTextField()),
                ('numero_votos', models.IntegerField(default=0)),
                ('elecciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='politica.eleccion')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
