# Generated by Django 4.1.8 on 2023-04-17 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogindexpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPageGalleryImage',
        ),
    ]
