# Generated by Django 4.1.8 on 2023-05-06 09:45

from django.db import migrations
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('blog', '0001_initial'),
        ('persona', '0002_personacategoria_personaindex_personalist'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='blog.BlogPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
